### ISSUE TITLE
'no-outline-none' should also check for 'border: none'.

### ISSUE THREAD

**Issue by alainEHV** [ronilaukkarinen/stylelint-a11y#8]
Right now, this scenario triggers an error/warning for the 'no-outline-none' rule:

```SCSS
&:focus {
    border: transparent;
    outline: none;
}
```

But these do _not_ trigger an error/warning:

```SCSS
&:focus {
    border: 0;
    outline: none;
}

&:focus {
    border: none;
    outline: none;
}
```

Looking at the code for the 'no-outline-none' rule, adding an extra check for 'none' should be a small change.
Assuming there's no underlying reason to ignore 'none'.

Some more work might be needed to debug why `border: 0` does not trigger any warning.
